CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    chip TEXT NOT NULL,
    board TEXT NOT NULL,
    ip TEXT NOT NULL,
    actions TEXT DEFAULT ''
);
